debug: false

kuluagent:
  car:
    boss: 1
    worker: 0
    backlog: 1024
    port: 7081
    timeout: 3000
  watch:
    boss: 1
    worker: 0
    backlog: 1024
    port: 7082
    timeout: 3000

# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
# Redis服务器地址
    host: 192.168.1.251
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password:
# 连接超时时间（毫秒）
    timeout: 60000
# 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 50
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
  # 连接池中的最大空闲连接
        max-idle: 5
  # 连接池中的最小空闲连接
        min-idle: 5

